version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: dockerfile.prod
    image: etl-backend-mercado-spot:latest
    container_name: etl-backend-mercado-spot
    ports:
      - "8095:8095"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8095
      - SPRING_DATASOURCE_URL=${SUPERBASE_URL}
      - SPRING_DATASOURCE_USERNAME=${SUPERBASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${SUPERBASE_PASS}
      - JWT_SECRET=${JWT_FIRMA}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - LOGGING_FILE_NAME=${LOGGING_FILE_NAME}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./.env:/app/.env:ro
    restart: unless-stopped