# Dockerfile.dev
FROM openjdk:17-jdk-slim

WORKDIR /app
COPY target/*.jar app.jar

# GC optimizado para desarrollo (menor pausa)
ENV JAVA_OPTS="-Xms512m -Xmx1g \
    -XX:+UseG1GC \
    -XX:MaxGCPauseMillis=100 \
    -XX:+PrintGCDetails \
    -XX:+PrintGCDateStamps"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]