spring.application.name=Mercado_Spot

# definimos un puerto y una URL para entrar con swagger
server.port=8080

# agregamos los datos para la conexion
spring.datasource.url=${SUPERBASE_URL}
spring.datasource.username=${SUPERBASE_USER}
spring.datasource.password=${SUPERBASE_PASS}

# agregamos configuraciones de hibernate para ver en terminal
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# visualizamos las querys al momento de la realizacion de la peticion
spring.jpa.properties.hibernate.format_sql=true

# agregamos el volumen para manejar tanto videos como fotos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

# para ver los errores
logging.level.org.springframework.security=DEBUG